ترجمه مساله‌های ۳۵، ۳۶ و ۳۷
marhale3/marhale3.github.io pull request #12
Opened 2021-03-22 12:05 UTC by ekm507

2021-03-22 13:33 UTC, ATofighi requested changes
سلام.

از مشارکت شما در ترجمه سپاس‌گزارم.

چندتا نکته به ذهنم رسید که کامنت گذاشتم، اگر وقت داشتید لطفا بررسیشون کنید و اصلاحشون کنید.

ممنون.
علیرضا

2021-03-22 13:33 UTC, ATofighi commented on _posts/1111-11-11-036.double-base-palindromes.html
>  ---
چون دیگر کد اچ‌تی‌ام‌الی داخل این فایل نیست، بهتر است فرمت آن به مارک‌داون تغییر کند، یعنی اسم فایل از
```
1111-11-11-036.double-base-palindromes.html 
```
به
```
1111-11-11-036.double-base-palindromes.md
```
تبدیل شود.

2021-03-22 13:33 UTC, ATofighi commented on _posts/1111-11-11-036.double-base-palindromes.html
> +عدد دهدهی ۵۸۵ = ۱۰۰۱۰۰۱۰۰۱ (باینری) در هر دو مبنا متقارن است.
فرمول‌های لتک هم پشتیبانی می‌شه، اینجا برای اینکه اندیس زیرین مبنای ۲ رو هم داشته باشیم، می‌شد یک دلار اول و آخر فرمول گذاشت و از آندرلاین برای اندیس‌گذاری استفاده کرد. یعنی می‌شد اینجوری نوشت:
```
$585 = (1001001001)_2$
```

2021-03-23 12:42 UTC, ekm507 commented on _posts/1111-11-11-036.double-base-palindromes.html
>  ---
انجام شد

2021-03-23 12:44 UTC, ekm507 commented on _posts/1111-11-11-036.double-base-palindromes.html
> +عدد دهدهی ۵۸۵ = ۱۰۰۱۰۰۱۰۰۱ (باینری) در هر دو مبنا متقارن است.
این تغییری که گفته بودی رو دادم.
 ولی من که دارم می‌نویسم، با چه برنامه‌ای باید این فایل رو تماشا کنم که این‌ها رو درست نشون بده؟

2021-03-23 12:49 UTC, ekm507 commented
دو تا تغییری که گفته‌بودی رو دادم.

2021-03-23 13:10 UTC, ATofighi commented on _posts/1111-11-11-036.double-base-palindromes.html
> +عدد دهدهی ۵۸۵ = ۱۰۰۱۰۰۱۰۰۱ (باینری) در هر دو مبنا متقارن است.
اگه داکر و داکرکامپوز نصب داری، اگه دستور 
```
docker-compse up
```
رو بزنی توی ترمینال، بعد روی 
```
http://localhost:4000
```
بالا میاد سایت، تغییری هم بدی اعمال می‌شه و می‌تونی ببینی. (۳۰ ثانیه طول می‌کشه فقط اعمال کنه تغییر رو)

2021-03-23 13:10 UTC, ATofighi approved these changes

2021-03-23 13:11 UTC, ATofighi commented
<div dir="rtl">
ممنون.
</div>

2021-03-23 13:11 UTC, merged